apache/mynewt-site

- custom-theme/css/custom.css
Restricting the height was creating multiple scrollable areas that were
confusing.
MYNEWT-157
> Don't restrict height of sidebar and docs

- docs/os/core_os/memory_pool/OS_MEMPOOL_BYTES.md
- docs/os/core_os/memory_pool/OS_MEMPOOL_SIZE.md
- docs/os/core_os/memory_pool/memory_pool.md
- docs/os/core_os/memory_pool/os_memblock_put.md
- docs/os/core_os/memory_pool/os_mempool_init.md
- mkdocs.yml
Finished memory pool documentation.
> os mempool

- docs/os/core_os/task/os_task_count.md
- docs/os/core_os/task/os_task_info_get_next.md
- docs/os/core_os/task/os_task_init.md
- docs/os/core_os/task/os_task_sanity_checkin.md
- docs/os/core_os/task/task.md
Committed documentation for os tasks
> MYNEWT-146: add task documentation to core os manual

- docs/os/core_os/sanity/os_sanity_check_init.md
- docs/os/core_os/sanity/os_sanity_check_register.md
- docs/os/core_os/sanity/os_sanity_check_reset.md
- docs/os/core_os/sanity/os_sanity_task_checkin.md
- docs/os/core_os/sanity/os_sanity_task_init.md
- docs/os/core_os/sanity/sanity.md
- docs/os/core_os/task/task.md
- mkdocs.yml
This is the documentation for the sanity task.
> Sanity docs

- custom-theme/community.html
- docs/documentation.md
- docs/os/get_started/introduction.md
Corrected a typo in the community page
> Community Page 

- docs/os/get_started/project1.md
1. Streamlined documentation
2. Made it conversational
3. Removed redundancy
4. Added Conclusion
> Changes to Blinky Project1.md

- docs/os/get_started/vocabulary.md
Minor edits
rmoved eggshell 
replace old terms with newer ones
> Changes to Vocabulary.md

- docs/os/modules/hal/hal.md
- docs/os/modules/hal/hal_api.md
- docs/os/modules/hal/hal_cputime/hal_cpu_timer.md
- docs/os/modules/hal/hal_creation.md
- docs/os/modules/hal/hal_in_libraries.md
- docs/os/modules/hal/hal_uart/hal_uart.md
- mkdocs.yml
This did several things
1) added subdirectories for each hal interface
2) added an overview
3) added a creating a new HAL
4) Added a writing libraries with HAL support
5) Added a table of APIs
6) Added UART
> Mynewt 191

- docs/os/tutorials/air_quality_sensor.md
Example is about senseair CO2 sensor being connected to STM32F3 board.
> Start of tutorial on how to create a custom dev happen.

- .editorconfig
- .gitignore
- custom-theme/base.html
- custom-theme/breadcrumbs.html
- custom-theme/css/custom.css
- custom-theme/manual_links.html
This adds three links above the docs to the left of the breadcrumbs.
> links to manuals for doc page header

- docs/os/core_os/mynewt_os.md
- docs/os/core_os/os_init.md
- docs/os/core_os/os_start.md
- docs/os/core_os/os_started.md
Added OS fundamental documentation.
> OS fundamental documentation

- docs/newt/newt_linux.md
- docs/newt/newt_mac.md
- docs/newt/newt_ops.md
- docs/os/get_started/vocabulary.md
minor edits; 
change to newer terms; and 
removed redundancies
> Changes to Newt Docs

- custom-theme/base.html
- custom-theme/css/custom.css
- custom-theme/js/base.js
- custom-theme/nav.html
Ensure that the menu is visible and accessible regardless of its height or viewport scroll.
> Make the doc table of contents position fixed

- docs/os/modules/hal/hal_gpio/hal_gpio.md
> Mynewt 182

- custom-theme/css/custom.css
- custom-theme/nav.html
This change puts a submenu under the navigation 'Docs' wth a link to each documentation related manual.
> Create a documentation drop down menu

- docs/os/tutorials/arduino_zero.md
amend instructions to show arduino zero and arduino zero pro
> MYNEWT-242

- docs/os/modules/testutil/test_case.md
- docs/os/modules/testutil/test_decl.md
- docs/os/modules/testutil/testutil.md
- docs/os/tutorials/unit_test.md
- mkdocs.yml
I also made some minor code changes which will appear in a pull request to the other repo.
> final doc changes for documenting building test libraries

- docs/newt/newt_linux.md
- docs/os/get_started/cross_tools.md
- docs/os/get_started/native_tools.md
- docs/os/get_started/project1.md
- docs/os/get_started/project_create.md
- mkdocs.yml
a tutorial on how to create a project
> Mynewt 247

- docs/newtmgr/installing.md
- docs/newtmgr/project-slinky.md
- docs/newtmgr/project-target-slinky.md
- mkdocs.yml
rewrite newtmgr tutorials for new newt and cleaup
> MYNEWT-214

- docs/os/tutorials/STM32F303.md
rewrite the STMF3Discovery tutorial for new newt commands
> MYNEWT-251

- docs/os/tutorials/Olimex.md
more changes for Olimex.  Had some left over refernces to the
git clone method/
> MYNEWT-250

- docs/os/modules/json/json.md
- docs/os/modules/json/json_encode_object_entry.md
- docs/os/modules/json/json_encode_object_finish.md
- docs/os/modules/json/json_encode_object_key.md
- docs/os/modules/json/json_encode_object_start.md
- docs/os/modules/json/json_read_object.md
> libs/json; Start documenting the API. Missing array docs and

- custom-theme/base.html
- custom-theme/css/custom.css
- custom-theme/css/v2.css
- custom-theme/landing.html
- custom-theme/main-banner.html
- custom-theme/nav.html
- custom-theme/quick-start.html
- docs/extra.css
- mkdocs.yml
+ removes a lot of the bootstrap override customizations
> Banner and landing page styling

- docs/os/tutorials/STM32F303.md
- docs/os/tutorials/pin-wheel-blinky.md
Add a link to the pin-wheel modifications to the STM32F303 page.
Add a new page with how to modify blinky to do the pin wheel.
> Add pin-wheel mod 

- docs/os/tutorials/bleprph/bleprph-intro.md
A couple of broken links in the Tutorials
> Broken Links

- docs/os/core_os/callout/callout.md
- docs/os/core_os/event_queue/event_queue.md
- docs/os/core_os/heap/heap.md
- docs/os/core_os/mbuf/mbuf.md
- docs/os/core_os/memory_pool/memory_pool.md
- docs/os/core_os/mqueue/mqueue.md
- docs/os/core_os/msys/msys.md
- docs/os/core_os/mutex/mutex.md
- docs/os/core_os/sanity/sanity.md
- docs/os/core_os/semaphore/semaphore.md
- docs/os/core_os/task/task.md
- docs/os/core_os/time/os_time.md
- mkdocs.yml
Added function descriptions from each function's doc page to the list of functions for each topic.
> Changed Core OS Function Lists to Tables With Descriptions

- docs/os/tutorials/air_quality_sensor.md
- docs/os/tutorials/bletiny_project.md
Fixed a few things in the STMF3 Air Quality tutorial and the NRF52 BLE Tutorial
> Additions and fixes to Tutorials

- docs/os/modules/split/split.md
- mkdocs.yml
Here is documentation for the split image design and usage
> add documentation for split images

- docs/newt/newt_intro.md
also removed whitespace at end of lines
> changes to add more detail on bsp porting

- docs/newt/newt_intro.md
> MYNEWT-126

- docs/os/tutorials/bletiny_project.md
As a newcomer, it wasn't immediately obvious what what serial connection parameters I should use to connect
> Elaborated on serial connection parameters

- docs/network/ble/ini_stack/ble_statpkg.md
No longer need to do all the code additions to enable stats pkg.
> Updated stats pkg init

- docs/os/tutorials/blinky_console.md
- mkdocs.yml
Since Blinky doesn't have an event queue it's trickier to add
console/shell to it.
> Added Console tutorial for blinky

- docs/os/modules/sysinitconfig/sysconfig_error.md
- docs/os/modules/sysinitconfig/sysinitconfig.md
- docs/os/tutorials/add_newtmgr.md
1) Updated System Configuration and Initialization Document for new system initialization implementation.
2) Updated Validation and Error Messages page to use Priority Violation Error Message.
3) Updated Enable Newtmgr in any app to reflect new system initialization implementation and in the code change for bletiny app.
4) Updated examples that use sys/log to sys/log/full.
> Update Docs for new system start up and initialization implementation.

- docs/os/tutorials/air_quality_ble.md
- docs/os/tutorials/air_quality_sensor.md
Updated based on Aditi's new code and the refactored BLE APIs
> Updated Air Qiuality Tutorial

- docs/os/modules/drivers/driver.md
- docs/os/modules/drivers/flash.md
- docs/os/modules/drivers/mmc.md
- docs/os/modules/fs/fatfs.md
- docs/os/modules/fs/fs/fs.md
- mkdocs.yml
> Adding documentation for FAT/MMC/Flash

- .gitignore
- README.md
- requirements.txt
Use more typical Python setup.
> Use virtualenv/pip for python setup

- docs/newt/command_list/newt_sync.md
- docs/newtmgr/command_list/newtmgr_config.md
- docs/newtmgr/command_list/newtmgr_conn.md
- docs/newtmgr/command_list/newtmgr_crash.md
- docs/newtmgr/command_list/newtmgr_datetime.md
- docs/newtmgr/command_list/newtmgr_echo.md
- docs/newtmgr/command_list/newtmgr_fs.md
- docs/newtmgr/command_list/newtmgr_image.md
- docs/newtmgr/command_list/newtmgr_logs.md
- docs/newtmgr/command_list/newtmgr_mpstats.md
- docs/newtmgr/command_list/newtmgr_reset.md
- docs/newtmgr/command_list/newtmgr_run.md
- docs/newtmgr/command_list/newtmgr_stat.md
- docs/newtmgr/command_list/newtmgr_taskstats.md
- docs/newtmgr/overview.md
- docs/os/tutorials/add_newtmgr.md
- mkdocs.yml
1) Updated Newtmgr command guide.
2) Fixed formatting in newt sycn command.
3) Added nmgr_uart to enabling newtmgr in any app
> Updated newtmgr command guide, added ngmr_uart to newtmgr tutorial, and minor formatting

- docs/os/modules/bootloader/bootloader.md
This fixes a lot of small issues on the generated bootloader docs.
> Fix style in bootloader markdown

- custom-theme/footer.html
title says it all 
why ? to get more people to engage in the amazing community around mynewt
icon/logo is debateable c&c on it 
thanks
> slack logo in footer

- custom-theme/community.html
community slack link . req by sterling
> community slack link

- docs/newtmgr/command_list/newtmgr_mpstats.md
- docs/newtmgr/command_list/newtmgr_taskstats.md
- docs/newtmgr/install_linux.md
- docs/newtmgr/install_mac.md
- docs/newtmgr/overview.md
- docs/os/modules/devmgmt/customize_newtmgr.md
- docs/os/modules/devmgmt/oicmgr.md
- docs/os/tutorials/add_newtmgr.md
- docs/os/tutorials/project-nrf52-slinky.md
- docs/os/tutorials/project-sim-slinky.md
- docs/os/tutorials/project-stm32-slinky.md
- mkdocs.yml
Name of commands changed: taskstats->taskstat and mpstats->mpstat
> MYNEWT-761 Update 1.1 doc for  newtmgr taskstats/mpstats commands.

- docs/os/tutorials/bleprph/bleprph-app.md
**Please merge into 1.0 and latest doc repo.**
> Fixed typo: myblerph should be myperiph

- docs/os/tutorials/ota_upgrade_nrf52.md
- mkdocs.yml
Please do not merge until Chris has a chance to review.
> Tutorial on over-the-air image upgrade.

- deploy.sh
We need to automate the generation of the documentation site. The first
step is getting the existing scripts to run on linux.
> Support running the deploy script on linux

- docs/os/modules/sysinitconfig/sysconfig_error.md
> Added note that a pkg may override its own settings.

- docs/network/ble/ble_hs/ble_gap/ble_gap.md
- docs/network/ble/ble_hs/ble_gap/definitions/ble_gap_defs.md
- docs/network/ble/ble_hs/ble_gap/functions/ble_gap_ext_connect.md
- docs/network/ble/ble_hs/ble_gap/functions/ble_gap_ext_disc.md
- docs/network/ble/ble_hs/ble_gap/functions/ble_gap_read_le_phy.md
- docs/network/ble/ble_hs/ble_gap/functions/ble_gap_set_prefered_default_le_phy.md
- docs/network/ble/ble_hs/ble_gap/functions/ble_gap_set_prefered_le_phy.md
- docs/network/ble/ble_hs/ble_gap/functions/ble_gap_set_priv_mode.md
- docs/network/ble/ble_intro.md
- mkdocs.yml
This PR is an updated version of #216.
> Documetation updates for Bluetooth 5 (Updated #216)

- docs/os/tutorials/segger_rtt.md
> Added note on J-Link versions and input char limits.

- docs/os/tutorials/sensors/sensor_thingy_lis2dh12_onb.md
- mkdocs.yml
Fixed wording on Sensor tutorial sidebar
> Fixed typo in sensor_set_poll_rate_ms function.

- docs/os/tutorials/project-stm32-slinky.md
- docs/os/tutorials/tutorials.md
- mkdocs.yml
1. Changed Image Upgrade and Managment to "Remote Device Management"
2. Cleaned Tutorial Overview page and added sensors tutorial.
3. Updated project slinky on olimex with new taskstat output.
> Cleaned up outline of tutorials.

- custom-theme/landing.html
Signed-off-by: Francois Berder <fberder@outlook.fr>
> Fix links for 6LoWPAN clicker and chipKIT wifire

- docs/newt/install/newt_windows.md
- docs/os/get_started/cross_tools.md
- docs/os/tutorials/nRF52.md
update instructions for windows installation
update nrf52 blinky tutorial to use nrf52dk instead of nrf52pdk
> update instructions for windows installation

- serve.py
`serve.py` was updated to run on both Python2 and 3.
> Update serve.py script for Python3 compatibility

- build.py
- custom-theme/choose_doc_version.html
- docs/documentation.md
- mkdocs.yml
Add docs for v1.6.0 and remove versioned documentation, generating pages from release tags.
> Build docs from tags

- custom-theme/css/custom.css
- custom-theme/footer.html
- custom-theme/main.html
Fix few issues pointed by whimsy.apache.org/site/project/mynewt.
> Make homepage more compliant with ASF recommendations

- docs/download.md
This relates to the latest release
> URGENT: Typo: newmgr => newtmgr

- requirements.txt
Specifies the jinja2 version required by other packages.
> site: update requirements

- custom-theme/about.html
- custom-theme/community.html
- custom-theme/cve.html
- custom-theme/footer.html
- custom-theme/landing.html
- custom-theme/main.html
- custom-theme/nav.html
- custom-theme/talks.html
- docs/about.md
- docs/cve.md
- docs/pages/securitybullets.md
- docs/quick-start.md
- mkdocs.yml
Adds new page with CVE listing for improved security awareness.
Updates outdated information on main pages, especially 'About' section.
Fixes navigation bar not showing currently active page and a number of other minor bugs, like not working links.
> Site updates

- .github/workflows/deploy-site.yml
Disables automated website deployment on forks.
> ci: Update automated deployment job

- .github/workflows/deploy-site.yml
Adds explicit write permissions for creating PRs.
> ci: Update permissions for `Deploy Site` workflow

- custom-theme/.htaccess
.htaccess file is introduced to configure Content-Security-Policy for Youtube. This is based on example on how to embed yt videos from privacy-website.
> custom-theme/talks: Configure Content-Security-Policy for Youtube

- build.py
Adjust build.py so that .htaccess file gets copied into /site directory
> adjust build.py

- deploy.sh
Adjust deploy.sh so that it copies .htaccess file properly
> adjust deploy.sh

- custom-theme/footer.html
Add Privacy Policy button to footer.
All ASF websites must link to the Privacy Policy.
Please see **https://whimsy.apache.org/site/project/mynewt** for mynewt website checks
> custom-theme: update footer
