apache/mynewt-site

- docs/os/get_started/cross_tools.md
Newt works with OpenOCD 0.9.0 as well (not just 0.8.0).  I am the one who added this incorrect note originally.  I didn't realize we had added 0.9.0 support!
> Remove incorrect OpenOCD 0.8.0 requirement.

- docs/network/ble/ini_stack/ble_ini_intro.md
- docs/network/ble/nimble_setup.md
I noticed some issues with the BLE user guide:
* Some of the steps assumed the user was building from the core directory rather than from their project directory.
* Copying bletiny's pkg.yml and main.c files is problematic; the files need to be customized for the new app.
* Some minor grammar / typo fixes.
> Nimble doc fixes

- docs/os/modules/stats/stats.md
An extra space before the closing triple-quotes for the first code block seems
to cause the clode block to not be closed and the rest of the page is messed
up. This is a difference between the Markdown renderer on Github and the Mkdocs
renderer used to create the documentation on the website.
Signed-off-by: Sam Bristow <sam.bristow@gmail.com>
> Remove rogue space in stats documentation

- docs/network/ble/bletiny_api.md
I removed the "b show svc" command from bletiny in order to make the
image smaller.  This command was redundant, as "b show chr" does the
same thing.
> Remove reference to deleted "show svc" command.

- docs/os/tutorials/add_newtmgr.md
Update the Enabling Newt Manager in any app to no longer tell the user that they must call mgmt_evq_set function since oicmgr no longer requires the caller to call mgmt_evq_set() and the call is taken out of slinky_oic app.
> No need to explicitly call mgmt_evq_set when using default os event queue

- docs/newtmgr/command_list/newtmgr_conn.md
- docs/newtmgr/command_list/newtmgr_crash.md
1) Fixed problem with  `newtmgr conn add` command parameters not showing  up in the document. Use `&lt;` and `&gt;` instead of `< `and `>`.
2) Removed extra `;` in the `newtmgr crash` command usage text.
> Fix minor typos in the newtmgr conn add and newtmgr crash commands

- docs/os/core_os/context_switch/context_switch.md
- docs/os/core_os/context_switch/os_sched_remove.md
- docs/os/core_os/memory_pool/memory_pool.md
- docs/os/core_os/memory_pool/os_mempool_info_get_next.md
- docs/os/core_os/task/os_task_remove.md
- docs/os/core_os/task/task.md
- docs/os/get_started/project_create.md
- docs/os/get_started/serial_access.md
- docs/os/modules/bootloader/bootloader.md
- docs/os/tutorials/arduino_zero.md
- docs/os/tutorials/blinky_primo.md
- docs/os/tutorials/nRF52.md
- docs/os/tutorials/olimex.md
- docs/os/tutorials/project-target-slinky.md
- mkdocs.yml
1) Updated blinky for arduino zero, arduino primo, olimex, nRF52 -  
Removed features, updated paths, general cleanup to make tutorials more consistent
2) Use updated olimex diagrams that shows power input select jumper location
so user can configure power source from JTAG/SWD
3) Fix typo in bleprph tutorial.
4) Updated Concepts section to use updated newt target -h output
5) Updated newt install  for Mac and linux to use updated newt -h output.
6) Updated newt install for linux for GO version 1.6
7) Remove duplicate instance of Air Quality Sensor project from document tree
8) Removed embedded LUA from doc tree.
> Various Updates to Doc to reflect 1.0 release

- docs/faq/go_env.md
- docs/newt/install/newt_mac.md
- docs/newtmgr/install_linux.md
- docs/newtmgr/install_mac.md
- docs/os/introduction.md
- docs/os/tutorials/add_newtmgr.md
- docs/os/tutorials/project-slinky.md
- mkdocs.yml
1) Modified newt_mac.md to use brew
2) Created newtmgr/install_mac.md that documents how to install newtmgr using brew.
3) Moved and updated newtmgr/installing.md to install_linux.md that documents how to install newtmgr from source on Linux.
4) Added a new "Setting Up Go Environment to Contribute to Newt and Newtmgr tool" page under Appendix.  Installing newt and newtmgr on Mac documents tell the user to reference this page if they want to contribute.
5) Updated URL references in os/introduction to point to new installation pages.
> Documentation for installing newt and newtmgr using brew

- docs/faq/go_env.md
1) Reorganized and updated the Contributing to Newt and Newtmgr Tools page to reflect the separate newtmgr git repo.
2) Added a note to indicate this is the setup to use if a user running on the Linux platform
wants the latest updates from master.
> Updated doc to reflect separate newtmgr repo

- docs/faq/go_env.md
- docs/newt/install/newt_linux.md
- docs/newtmgr/install_linux.md
- docs/os/get_started/native_install_intro.md
- docs/os/get_started/native_tools.md
- docs/os/get_started/project_create.md
- docs/os/tutorials/add_newtmgr.md
- docs/os/tutorials/add_shell.md
- docs/os/tutorials/arduino_zero.md
- docs/os/tutorials/blehci_project.md
- docs/os/tutorials/bletiny_project.md
- docs/os/tutorials/blinky.md
- mkdocs.yml
We can leave this PR open  so I can make any other updates as needed after others  have tested the installation.
Fixed ordering of installation sequence of newt tool and native tool chain.
> Minor edits for installing newt and newtmgr from debian packages

- docs/os/get_started/native_install_intro.md
- docs/os/tutorials/blinky_stm32f4disc.md
- docs/os/tutorials/rbnano2.md
1) Fixed broken link to install openocd debugger in redbear nano2 and stm32f4disc blinky tutorials
2) Fixed broken link to installing native toolchain in the the native installation introduction page.
> Fixed broken links.

- docs/newt/install/newt_linux.md
- docs/newtmgr/install_linux.md
Should be debian-mynewt instead of debian-package
> Fixed incorrect repo urls in mynewt.list source list.

- docs/newt/install/newt_linux.md
- docs/newtmgr/install_linux.md
1) Add note that we tested newt and newtmgr tool binaries and installation on Ubuntu version 16 and may
not work on earlier versions.
2) Provided instructions on how to manually download and install binary if user doesn't want to upgrade Ubuntu. But recommend they will want to upgrade if installing from source.
> Note install for newt and newtmgr may not work on Ubuntu version < 16

- docs/newt/install/newt_windows.md
- docs/newtmgr/install_windows.md
- docs/os/get_started/project_create.md
- docs/os/tutorials/arduino_zero.md
- docs/os/tutorials/blinky_primo.md
- docs/os/tutorials/blinky_stm32f4disc.md
- docs/os/tutorials/olimex.md
- docs/os/tutorials/project-stm32-slinky.md
- docs/os/tutorials/rbnano2.md
- docs/os/tutorials/wi-fi_on_arduino.md
1. Fix typo in newt install on Windows
2. Tell Windows users to set vers  to 0-dev and use the master branch for the apache-mynewt-core and mynewt_arduino_zero repo.
3. More boards need to install usb driver on Windows 7 than Windows 10.
4. Fix typo in newtmgr install on Windows
5. Add instructions to install mbed serial port driver for primo and nano2 .
This does not include the additional instructions for Windows 7 users to install updated driver from  arduino to get primo to work. Need to decide if we want to package the drivers and put on runtimeco.
> Update installation instructions for Windows

- docs/faq/ide.md
- docs/newt/install/newt_windows.md
- docs/os/get_started/native_install_intro.md
- docs/os/tutorials/blinky_primo.md
1) IDE: Added note to ensure bash is in the path.
2) IDE: Added path to gdb.exe
3) Windows Installation: Added note to include bash in path.
4) Primo blinky tutorial: Added instructions to download and install arduino primo drivers.
> Updated ide, windows installation, and primo blinky tutorial.

- docs/newt/command_list/newt_run.md
For version  1.1  added a note that when version number is not provided, create-image step is skipped for a bootloader target, and prompts the user to enter a version for an application target.
> MYNEWT-764 Document 1.1 newt run command behavior when version is not provided

- docs/os/tutorials/blinky.md
- docs/os/tutorials/nRF52.md
- mkdocs.yml
Use nRF52 Development Kit (nRF52-DK)  in blinky nrf52 tutorial to avoid confusion that the patched openocd currently works with nRF52-DK
> Use nRF52 Development Kit (nRF52-DK)  in blinky nrf52 tutorial

- docs/os/tutorials/tasks_lesson.md
changed link from task_lesson1.png to task_lesson.png.  Please merged this into 1.0 and latest doc.
> Fix broken link to task_lesson.png

- docs/os/modules/stats/stats.md
**This PR can be merged into 1.0 and the latest documentation.** 
Use STATS_NAMES syscfg setting instead of STAT_NAMES_ENABLE compile flag to
enable stat names.
> Use STATS_NAMES syscfg setting

- docs/newtmgr/command_list/newtmgr_image.md
Added documentation for newtmgr image erase subcommand to support 
https://github.com/apache/incubator-mynewt-newt/pull/60
> MYNEWT-768 - add newtmgr image erase subcommand.

- custom-theme/breadcrumbs.html
- custom-theme/css/custom.css
- mkdocs.yml
Add settings and missing styling to get a link to the page you're viewing on the docs github repo. This will make contributing a lot easier, and will probably improve the quality of the documentation over time.
Had to remove the `float: right` on the breadcrumbs so they weren't crammed together with the github link (like it is originally in mkdocs).
> Add edit on github link

- docs/os/modules/shell/shell.md
This PR should be merged into 1.0 doc.  You can also merge this into the latest doc or just wait until the  PR for the 1.1 shell improvement doc is created. 
1) Removed the blinky shell example
2) Added a link the the enabling the Console and Shell tutorial as an example.
> Removed outdated shell example.

- custom-theme/base.html
This adds a helpful banner to alert users when they are browsing outdated versions of the docs. It looks like this:
> Add outdated documentation warning banner

- docs/os/tutorials/blinky_stm32f4disc.md
I have an older STM32F4Discovery with a different programmer (week 21, 2014), so the tutorial did not work for me. It was also missing information about udev rules. This should clear up both of those things (I hope!).
Thanks,
Jeremy
> added message about older ST-LINK programmers on the STM32F4Discovery

- docs/faq/answers.md
- docs/os/tutorials/codesize.md
- mkdocs.yml
1) Added a guide on how to reduce code size for an application
2) Reformatted FAQ with categories and listed the questions with links (and anchors) to the anwers.
3) Added a link in the FAQ to the reduce code size tutorial.
> Add how to reduce code size and reformat faq

- docs/faq/answers.md
- docs/faq/go_env.md
- docs/known_issues.md
- docs/newt/install/newt_linux.md
- docs/newt/install/newt_windows.md
- docs/newtmgr/install_linux.md
- docs/os/get_started/project_create.md
- mkdocs.yml
**PLEASE MERGE INTO DEVELOP AND 1.0 BRANCH**
1) Added note to change incubator-mynewt-core to mynewt-core
2) Added not to use Go 1.7.6 or higher if building from source
3) Created Known Issues page and added this issue to it.
> Add note about changing incubator-mynewt-core to mynewt-core

- docs/known_issues.md
- docs/os/get_started/project_create.md
- Removed rebuild as a workaround.
- Removed reason for failure.
> Updated note for HTTP redirect error.

- docs/os/tutorials/codesize.md
- Changed "newt target append" command was changed to  "newt target amend".
Forgot about the name change.
- Added missing "."
> Fixed typo: "append" should be "amend"

- docs/newt/command_list/newt_pkg.md
`newt pkg new` command now supports 'unittest' and 'app'.
> Update doc for newt pkg new command.

- docs/os/modules/logs/logs.md
The guide was out of date and specified to use cflags to specify the log level.
> Updated Log OS guide to use LOG_LEVEL syscfg setting.

- docs/newt/command_list/newt_debug.md
* Updated cflags=-DSTATS_NAME_ENABLE to use STATS_NAMES sysfg setting.
* Note that the same occurrence in the newt create-image command has been updated in this PR: https://github.com/apache/mynewt-site/pull/243
> Update newt debug example to use STATS_NAMES syscfg setting.

- docs/os/tutorials/tutorials.md
- mkdocs.yml
I find the tutorial table of contents in the sidebar to be difficult to navigate.  This PR organizes the table of contents by category.
I didn't put too much thought into how these get categorized, but I think it is a good starting point.  If we want to keep the tutorials categorized, then all comments are welcome.  Otherwise, feel free to reject this PR.
> Organize tutorial TOC by category.

- docs/newtmgr/command_list/newtmgr_config.md
- docs/newtmgr/command_list/newtmgr_conn.md
- docs/newtmgr/command_list/newtmgr_crash.md
- docs/newtmgr/command_list/newtmgr_datetime.md
- docs/newtmgr/command_list/newtmgr_echo.md
- docs/newtmgr/command_list/newtmgr_fs.md
- docs/newtmgr/command_list/newtmgr_image.md
- docs/newtmgr/command_list/newtmgr_logs.md
- docs/newtmgr/command_list/newtmgr_mpstats.md
- docs/newtmgr/command_list/newtmgr_reset.md
- docs/newtmgr/command_list/newtmgr_run.md
- docs/newtmgr/command_list/newtmgr_stat.md
- docs/newtmgr/command_list/newtmgr_taskstats.md
- docs/newtmgr/overview.md
- docs/os/tutorials/project-nrf52-slinky.md
- docs/os/tutorials/project-stm32-slinky.md
1. Update new global flags for newtmgr 1.1
2. Updated slinky tutorials
3. Updated newtmgr log show command usage.
4. Updated newtmgr stat command syntax.  In 1.0 you can use `newtmgr stat` with no arguments to get a list of stat names. The command no longer support this. You can only use `newtmgr stat list` to get the stat names
5. Typo fixes.
> MYNEWT-776 Update newtmgr docs for 1.1

- docs/os/get_started/cross_tools.md
Added installation instruction for missing libusb-0.1.4.dylib,libftdi1.2.dylib,
and libhidapi.0.dylib on Mac OS.
> Documented missing libraries for openocd on Mac OS.

- docs/os/modules/sensor_framework/sensor_driver.md
- docs/os/modules/sensor_framework/sensor_shell.md
- Added note about difference between sensor shell command and sensor device shell command.
- Fixed wrong link to bno055 shell implementation.
- Fixed broken link in sensor shell page.
> Added more details for sensor device shell command.

- docs/os/tutorials/ota_upgrade_nrf52.md
When log level is set to DEBUG, the extra logging causes communication to timeout and the upload fails. Lowering log level to INFO seems to fix the proble. We tell the user to do that so the tutorial does not fail.
> Updated ota upgrade tutorial to reduce log level.

- docs/os/modules/sensor_framework/sensor_create.md
- docs/os/modules/sensor_framework/sensor_framework_overview.md
- docs/os/tutorials/sensors/sensor_nrf52_bno055.md
The BNO055_CLI  setting changed from enabled to disabled by default.
In a previous commit, the tutorial was updated to tell the user to enable the setting in the newt target set command, but didn't update a note that told the user the setting was enabled by default.
This commit fixes the note so it doesn't say the setting is enabled by default.
> Fixed note about bno055 shell command setting.

- docs/os/tutorials/sensors/sensor_bleprph_oic.md
- docs/os/tutorials/sensors/sensor_nrf52_bno055_oic.md
- docs/os/tutorials/sensors/sensor_oic_overview.md
- docs/os/tutorials/sensors/sensors.md
- mkdocs.yml
- Added write up about thr mynewt smart device app in sensor tutorials overview page. Tell user to instal app from apple store and google play store.
- Added links to the android sensor source and ios sensor source.
- Added links from oic tutorials to sensor tutorials overview for installation instructions.
Note this assumes the the apps will be added to the apple store and the google pay store.
- Reordered Sensor Shell in Sensor Framework OS Guide Sidebar
> [DO NOT MERGE THIS UNTIL sensor apps are in apple and play store] Add links and notes about the mynewt smart device app.

- docs/os/get_started/docker.md
Generic instructions for downloading the extension pack. The current instructions contain a hard link to version 5.0.16 without any indication that this does not match the VirtualBox version (5.1.26) currently installed by Docker Toolbox.
> Fix version mismatch in VirtualBox Extension Pack download instructions

- docs/newt/install/newt_linux.md
- docs/newt/install/newt_mac.md
- docs/newt/install/newt_windows.md
- docs/newt/install/prev_releases.md
- docs/newtmgr/install_linux.md
- docs/newtmgr/install_mac.md
- docs/newtmgr/prev_releases.md
**NOTE: This PR updates the 1.2.0 docs to make it easier to update new releases. It does not have the updates needed for the 1.3.0 release.**
- Removed note that brew bottles are created for el-capitan.
Now we only release bottles for the latest(sierra) mac os.
- Removed output of brew commands
- Updated link for downloading debian packages manually from
debian-mynewt to binary-releases repo.
- Fixed link in previous windows releases to point to tar files instead of deb files
> Updated 1.2.0 install doc to simplify adding new releases

- docs/os/tutorials/air_quality_sensor.md
Targets were left at boot_nrf but first command was to set target to boot_primo.
> Updated target names

- docs/newt/install/newt_linux.md
Using the original instructions I got the following error after running `apt-get update`:
`N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://raw.githubusercontent.com/runtimeco/debian-mynewt/master latest InRelease' doesn't support architecture 'i386'`
The explanation for why this is needed is here: https://askubuntu.com/a/741411
> Added architecture to sources.list entry

- docs/os/tutorials/bleprph/bleprph-svc-reg.md
I've updated the page to use the current APIs and match with the current bleprph demo files. Please check this carefully as I'm new to Mynewt.
I think the first couple of paragraphs still need to be changed as several gatt services seem to be built into nimble rather than all listed in one gatt table like the old bleprph demo.
> Updated BLE Peripheral Project Service Registration Page

- docs/os/tutorials/bleprph/bleprph-intro.md
It appears as though this portion is now all handled via sysinit. Not 100% sure if a new link should be included to somewhere else.
> The NimBLE Stack Initialization page no longer exists

- docs/newt/command_list/newt_mfg.md
Presumably the same version as create-image rb_blinky ?
> newt mfg create appears to take a version now

- docs/os/tutorials/bleprph/bleprph-intro.md
Seems as though the bluetooth.com site has seen some changes last year. I used the wayback machine to dig up what the intended page was and found it's new location. If there are any other links to bluetooth.com documentation it wouldn't surprise me if they too are broken.
> Previous link was a 404, updated

- docs/os/modules/bootloader/bootloader.md
As step f is replacing slot1[index] and step i is copying scratch area to slot0[index], scratch area should contain data from slot1[index].
> Fix sector index during swap process

- docs/os/tutorials/air_quality_sensor.md
This fixes a broken example due to lack of `MYNEWT_VAL(x)` definition. PS: `shell.h` already includes `<syscfg/syscfg.h>` in `master` so this change will not be required when 1.4.0 comes out (but it doesn't hurt having it anyway).
> Fix building air quality example on mynewt 1.3.0

- docs/os/core_os/mqueue/mqueue.md
The example was missing an argument to os_mqueue_init for the processing function.
> Added processing function argument to os_mqueue_init

- docs/os/tutorials/bleprph/bleprph-svc-reg.md
The old link didn't work.  This one should.
> fix link to ble_gatt.h (nimble moved to separate repository)

- README.md
- extras/robots.txt
So that they do not appear in search results before the latest docs.
Fixes #473
> search results: disallow indexing of older doc versions

- custom-theme/main-banner.html
- docs/download.md
This also updates download page to container direct links to PGP and SHA512
as required by Apache standards.
> Add Mynewt 1.6.0 and NimBLE 1.1.0 release

- custom-theme/child_url.html
- custom-theme/choose_doc_version.html
- custom-theme/nested_toc.html
Just to clarify this, if someone goes today to https://mynewt.apache.org and navigates to a release from 1.3.0 and below, and starts using the left nav to choose pages to visit, most of those links are broken (404) because they are not normalized to remove the prepending uri. This fixes it by calling the url macro (see https://www.mkdocs.org/user-guide/custom-themes/#url).
> Fix nav link normalization for older releases

- custom-theme/community.html
- custom-theme/footer.html
- mkdocs.yml
This adds the slack URL to the global config, so no copy/paste URLs are distributed across the template files.
> Add slack url to global config

- .gitignore
- build.py
- custom-theme/landing.html
This updates the build system, to read BSP metadata including "name", "url", "description" and "arch", and auto-generate the list of supported boards in the landing page.
It requires that each BSP is updated with this metadata, and each new BSP has this metadata added to its "bsp.yml" file.
> Auto-generate supported board list from BSP metadata

- build.py
see: https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation#how-to-disable-the-warning
> Fix warning on deprecated usage of yaml.load

- custom-theme/landing.html
Fix link that goes to empty page.
Fixes https://github.com/apache/mynewt-core/issues/2397
> Update landing BLE link to network page

- docs/download.md
Following issues were fixed:
- there is no link to the KEYS file at
https://downloads.apache.org/mynewt/KEYS
- there is no mention of the need to verify downloads, nor
information on how to do so using the KEYS and sigs or hashes
- the core 1.9.0 link has a typo, so the link does not work
- it's not clear what the difference is between the core and newt
downloads. Are they both needed?
- the download page must not link to non-released software such as code
under development. Such links should be reserved for pages intended
for developers only.
- the download page must not link directly to mirror directories, as these
don't carry the sigs and hashes:
-- the Release Download link for MyNewt core 1.9.0 should be removed
-- Added direct links to source and binary releases
- fixed old releases …
> Update download page with comments from announce list moderator

- build.py
The build script now checks if 'bsp.exclude_site' has been set in board's bsp.yml, allowing certain boards to be excluded from the 'Supported Boards' section on the mynewt main page. Also, boards are now sorted alphabetically.
> site: update build.py

- custom-theme/css/custom.css
- custom-theme/talks.html
Due to Content Security Policy (CSP) restrictions
that block embedded videos, this commit replaces
<iframe> elements with hyperlinked thumbnails.
> custom-theme/talks: Replace iframe elements with thumbnails

- mkdocs.yml
Removes Google Analytics from the site to align with [ASF Data Privacy Policy](https://privacy.apache.org/faq/committers.html).
> mkdocs: Disable `google_analytics` in site config

- custom-theme/choose_doc_version.html
- docs/documentation.md
- mkdocs.yml
Adds the master branch documentation as an option to choose from the drop-down list in the `Documentation` section.
> documentation: add `master` as a selectable version

- docs/documentation.md
Adds the full version of the documentation, available at `Documentation` section in the nav-bar.
> docs: Add Mynewt Documentation in `.PDF` format

- README.md
Adds a snippet with `git clone` for the dependent repos. Updates deployment information.
> README: Update instructions for setup and deployment

- custom-theme/main.html
- versions/v0_9_0/mkdocs.yml
- versions/v1_0_0/mkdocs.yml
- versions/v1_1_0/mkdocs.yml
- versions/v1_2_0/mkdocs.yml
- versions/v1_3_0/mkdocs.yml
**Remove Google Analytics from mynewt Wesbiste**
The mynewt website is using Google Analytics on 2,239 pages in versions 0.9, 1.0, 1.1, 1.2 & 1.3 of its documentation. The ASF Privacy Policy[1][2] does not permit the use of Google Analytics on any ASF websites.
Please see https://github.com/apache/mynewt-core/issues/3366
> Remove Google Analytics from mynewt Wesbiste

- .github/workflows/deploy-site.yml
Change ubuntu version from 20.04 to 22.04 as Ubuntu 20.04 LTS runner has been removed on 2025-04-15.
See deprecation notice https://github.com/actions/runner-images/issues/11101
> Update workflow file

- .github/workflows/deploy-site.yml
Use python 3.8 in deploy-site workflow
> ci: use python 3.8

- .github/workflows/deploy-site.yml
- requirements.txt
- workflow will now use python 3.13
- use latest versions of all tools and plugins
Upgrading sphinx requires https://github.com/apache/mynewt-documentation/pull/128 to be merged
> Update requirements and use python 3.13 in workflow

- custom-theme/community.html
- custom-theme/main.html
- Get rid of externally loaded fonts. It is recommended in ASF Security Policy not to use any external resources. "ASF projects don’t have any reason to load Google Fonts from Google servers". Please see https://privacy.apache.org/faq/committers.html
- Use hosted Slack Icon file. instead of externally loaded. The Icon wasn't properly displayed.
Please see **https://whimsy.apache.org/site/project/mynewt** for mynewt website checks
> Remove externally loaded materials
